---
title: "Assignment4"
author: "Jeremy Knox"
date: "12/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(car)
library(userfriendlyscience)
library(knitr)
library(kableExtra)
library(effsize)
library(ggrepel)
library(reshape2)
library(stargazer)
```


Probabilities of Flood $(>5m)$
```{r}
#### Current ####
norm_ht = pnorm(5, mean=2.5, sd=3, lower.tail=F)
norm_lt = pnorm(5, mean=-2.5, sd=3, lower.tail=F)
one_ht = pnorm(5, mean=3.5, sd=3, lower.tail=F)
one_lt = pnorm(5, mean=-1.5, sd=3, lower.tail=F)
two_ht = pnorm(5, mean=4.5, sd=3, lower.tail=F)
two_lt = pnorm(5, mean=-0.5, sd=3, lower.tail=F)
three_ht = pnorm(5, mean=5.5, sd=3, lower.tail=F)
three_lt = pnorm(5, mean=0.5, sd=3, lower.tail=F)
df_norm = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)


#### 2020 and 2050 Assumptions ####
assumptions_2020 = c(0,0.0508,0.1524,0.2794)
assumptions_2050 = c(0,0.1778,0.4572,0.7874)

#### 2020  low assumptions_2020[2] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2020[2]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2020[2]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2020[2]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2020[2]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2020[2]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2020[2]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2020[2]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2020[2]), sd=3, lower.tail=F)
df_2020_low = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### 2020  mid assumptions_2020[3] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2020[3]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2020[3]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2020[3]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2020[3]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2020[3]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2020[3]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2020[3]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2020[3]), sd=3, lower.tail=F)
df_2020_mid = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### 2020  high assumptions_2020[4] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2020[4]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2020[4]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2020[4]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2020[4]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2020[4]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2020[4]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2020[4]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2020[4]), sd=3, lower.tail=F)
df_2020_high = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### 2050  low assumptions_2050[1] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2050[2]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2050[2]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2050[2]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2050[2]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2050[2]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2050[2]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2050[2]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2050[2]), sd=3, lower.tail=F)
df_2050_low = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### 2050  mid assumptions_2050[3] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2050[3]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2050[3]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2050[3]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2050[3]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2050[3]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2050[3]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2050[3]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2050[3]), sd=3, lower.tail=F)
df_2050_mid = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### 2050  high assumptions_2050[4] ####
norm_ht = pnorm(5, mean=  (2.5+assumptions_2050[4]), sd=3, lower.tail=F)
norm_lt = pnorm(5, mean= (-2.5+assumptions_2050[4]), sd=3, lower.tail=F)
one_ht = pnorm(5, mean=  (3.5+assumptions_2050[4]), sd=3, lower.tail=F)
one_lt = pnorm(5, mean= (-1.5+assumptions_2050[4]), sd=3, lower.tail=F)
two_ht = pnorm(5, mean=  (4.5+assumptions_2050[4]), sd=3, lower.tail=F)
two_lt = pnorm(5, mean= (-0.5+assumptions_2050[4]), sd=3, lower.tail=F)
three_ht = pnorm(5, mean= (5.5+assumptions_2050[4]), sd=3, lower.tail=F)
three_lt = pnorm(5, mean= (0.5+assumptions_2050[4]), sd=3, lower.tail=F)
df_2050_high = data.frame(norm_ht,norm_lt,one_ht,one_lt,two_ht,two_lt,three_ht,three_lt)

#### Data Frames ####
df_2020 = rbind(df_norm,df_2020_low,df_2020_mid,df_2020_high)
df_2050 = rbind(df_norm,df_2050_low,df_2050_mid,df_2050_high)

```
The following visiaulization are done in excel.